name: Export Category 

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Pick Category to Export. This corresponds to tabs in the 1572-B data matrix '
        required: true
        type: choice
        options:
        - housing_production
        - quality_of_life
        - housing_security
      geography:
        description: Pick Geography to Export (citywide, borough, puma).
        required: False
        type: choice
        options:
        - citywide
        - borough
        - puma

jobs:
  export:
    runs-on: ubuntu-20.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      
    strategy:
      matrix:
        geography:
          - puma
          - borough
          - citywide
        category:
          - housing_production
          - quality_of_life
          - housing_security
 
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-distutils
          sudo apt install -y gdal-bin
          curl -sSL https://install.python-poetry.org | python3 -
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4

      - name: Poetry Install
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry install      

      - name: dataloading
        run: ./ingest/data_library/dataloading.sh

      - name: export
        run: |
          poetry run python3 -m external_review.external_review_collate ${{matrix.geography}} ${{matrix.category}} 
          ./external_review/export_DO.sh export ${{matrix.geography}} ${{matrix.category}}


