name: Pytest

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/test.yml"
      - "poetry.lock"
      - pyproject.toml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-distutils
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

      - name: Poetry Install
        run: |
          . $HOME/.poetry/env
          pip install poetry
          poetry install

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.2' # The R version to download (if necessary) and use.
          
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            survey


      - name: Pytest
        run: |
          . $HOME/.poetry/env
          poetry run pytest -s
