name: Test Housing Securyt

on:
  workflow_dispatch:
  pull_request:
  #  paths:
  #    - "aggregate/PUMS/**.py"
  #    - "aggregate/housing_security/**.py"
  #    - "tests/housing_security/**.py"
  #    - "external_review/**.py"
  #    - "utils/**.py"
  #    - "resources/**"
  #    - ".github/workflows/test_housing_security.yml"

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.9.7'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-distutils
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4

      - name: Python packages install
        run: |
          python3 -m pip install --requirement requirements.txt
      
      - name: dataloading
        run: ./ingest/data_library/dataloading.sh

      - name: Pytest
        run: |
          export PATH=$PATH:$HOME/.local/bin
          python3 -m pytest -v tests/housing_security